spring:
  application.name: novelgrain-ddd-backend
  datasource:
    url: jdbc:mysql://localhost:3306/novelgrain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: shn666666
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    # IMPORTANT: Flyway connects to the server, not to a specific DB
    url: jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    user: root
    password: 123456
    # Create the schema (MySQL “schema” == database)
    create-schemas: true
    schemas: novelgrain
    default-schema: novelgrain
    locations: classpath:db/migration
    enabled: true

server.port: 8080

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui

logging.level:
  org.springframework: INFO
  org.hibernate.SQL: INFO

# 头像上传在服务器上的路径（Linux）
upload:
  base-dir: "/data/novelgrain/uploads"
