CREATE TABLE IF NOT EXISTS book_lists (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_list_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS book_list_books (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    book_list_id BIGINT NOT NULL,
    book_id BIGINT,
    title VARCHAR(120) NOT NULL,
    author VARCHAR(80),
    orientation VARCHAR(20),
    category VARCHAR(20),
    rating INT,
    review TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_list_books_list FOREIGN KEY (book_list_id) REFERENCES book_lists(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
